version: '2'

services:
  quotes-suggestions-service:
    image: "suggestions_service:local"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENVIRONEMENT: ${ENVIRONEMENT}
        SERVICE_NAME: ${QUOTES_SUGGESTIONS_SERVICE_NAME}
        PORT: ${QUOTES_SUGGESTIONS_PORT}
    environment:
      - ENVIRONEMENT=${ENVIRONEMENT}
      - SERVICE_NAME=${QUOTES_SUGGESTIONS_SERVICE_NAME}
      - PORT=${QUOTES_SUGGESTIONS_PORT}
      - DEFAULT_CACHE_TTL=${QUOTES_SUGGESTIONS_DEFAULT_CACHE_TTL}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    ports:
      - "5000:5000"
    expose:
      - 5000
    command: 'run'
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile
    expose:
      - 6379
    ports:
      - "6379:6379"
    restart: unless-stopped

  web:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
      - "8080:8080"
    depends_on:
      - quotes-suggestions-service
